server:
  port: 80

spring:
  resources:
    static-locations: classpath:/static
  mvc:
    static-path-pattern: /**
  freemarker:
    cache: false
    charset: utf-8
    template-loader-path: classpath:/templates
    suffix: .ftl
  application:
    name: mongo
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: exam

logging:
  config: classpath:log/logback-spring.xml